# curl  -H 'Content-Type:application/json;charset=UTF-8' http://localhost:8080/restaurant/rest/restaurants/10002/votes --user user@gmail.com:user
GET http://localhost:8080/restaurant/rest/restaurants/10002/votes
Authorization: Basic user@gmail.com user
Content-Type: application/json;charset=UTF-8

###

# curl  -i -X PUT http://localhost:8080/restaurant/rest/restaurants/10002/votes --user user@gmail.com:user
PUT http://localhost:8080/restaurant/rest/restaurants/10002/votes
Authorization: Basic user@gmail.com user

###
